-- SQL para atualizar previewUrls no Supabase
-- Execute no SQL Editor do Supabase Dashboard

-- 2000s-cam
UPDATE photo_packages SET "previewUrls" = '["https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/2000s-cam/preview-1.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/2000s-cam/preview-2.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/2000s-cam/preview-3.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/2000s-cam/preview-4.jpg"]'::jsonb WHERE LOWER(name) = LOWER('2000s Cam');
-- comic-book
UPDATE photo_packages SET "previewUrls" = '["https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/comic-book/preview-1.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/comic-book/preview-2.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/comic-book/preview-3.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/comic-book/preview-4.jpg"]'::jsonb WHERE LOWER(name) = LOWER('Comic Book');
-- conceitual
UPDATE photo_packages SET "previewUrls" = '["https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/conceitual/preview-1.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/conceitual/preview-2.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/conceitual/preview-3.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/conceitual/preview-4.jpg"]'::jsonb WHERE LOWER(name) = LOWER('Conceitual');
-- executive-minimalist
UPDATE photo_packages SET "previewUrls" = '["https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/executive-minimalist/preview-1.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/executive-minimalist/preview-2.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/executive-minimalist/preview-3.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/executive-minimalist/preview-4.jpg"]'::jsonb WHERE LOWER(name) = LOWER('Executive Minimalist');
-- fitness-aesthetic
UPDATE photo_packages SET "previewUrls" = '["https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/fitness-aesthetic/preview-1.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/fitness-aesthetic/preview-2.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/fitness-aesthetic/preview-3.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/fitness-aesthetic/preview-4.jpg"]'::jsonb WHERE LOWER(name) = LOWER('Fitness Aesthetic');
-- flight-mode
UPDATE photo_packages SET "previewUrls" = '["https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/flight-mode/preview-1.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/flight-mode/preview-2.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/flight-mode/preview-3.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/flight-mode/preview-4.jpg"]'::jsonb WHERE LOWER(name) = LOWER('Flight Mode');
-- food-mood
UPDATE photo_packages SET "previewUrls" = '["https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/food-mood/preview-1.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/food-mood/preview-2.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/food-mood/preview-3.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/food-mood/preview-4.jpg"]'::jsonb WHERE LOWER(name) = LOWER('Food Mood');
-- golden-hour
UPDATE photo_packages SET "previewUrls" = '["https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/golden-hour/preview-1.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/golden-hour/preview-2.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/golden-hour/preview-3.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/golden-hour/preview-4.jpg"]'::jsonb WHERE LOWER(name) = LOWER('Golden Hour');
-- life-aesthetic
UPDATE photo_packages SET "previewUrls" = '["https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/life-aesthetic/preview-1.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/life-aesthetic/preview-2.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/life-aesthetic/preview-3.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/life-aesthetic/preview-4.jpg"]'::jsonb WHERE LOWER(name) = LOWER('Life Aesthetic');
-- makeup
UPDATE photo_packages SET "previewUrls" = '["https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/makeup/preview-1.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/makeup/preview-2.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/makeup/preview-3.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/makeup/preview-4.jpg"]'::jsonb WHERE LOWER(name) = LOWER('Makeup');
-- mirror-selfie
UPDATE photo_packages SET "previewUrls" = '["https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/mirror-selfie/preview-1.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/mirror-selfie/preview-2.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/mirror-selfie/preview-3.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/mirror-selfie/preview-4.jpg"]'::jsonb WHERE LOWER(name) = LOWER('Mirror Selfie');
-- neo-casual
UPDATE photo_packages SET "previewUrls" = '["https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/neo-casual/preview-1.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/neo-casual/preview-2.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/neo-casual/preview-3.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/neo-casual/preview-4.jpg"]'::jsonb WHERE LOWER(name) = LOWER('Neo Casual');
-- nomade
UPDATE photo_packages SET "previewUrls" = '["https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/nomade/preview-1.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/nomade/preview-2.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/nomade/preview-3.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/nomade/preview-4.jpg"]'::jsonb WHERE LOWER(name) = LOWER('Nomade');
-- outfit
UPDATE photo_packages SET "previewUrls" = '["https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/outfit/preview-1.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/outfit/preview-2.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/outfit/preview-3.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/outfit/preview-4.jpg"]'::jsonb WHERE LOWER(name) = LOWER('Outfit');
-- pet-shot
UPDATE photo_packages SET "previewUrls" = '["https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/pet-shot/preview-1.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/pet-shot/preview-2.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/pet-shot/preview-3.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/pet-shot/preview-4.jpg"]'::jsonb WHERE LOWER(name) = LOWER('Pet Shot');
-- quiet-luxury
UPDATE photo_packages SET "previewUrls" = '["https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/quiet-luxury/preview-1.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/quiet-luxury/preview-2.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/quiet-luxury/preview-3.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/quiet-luxury/preview-4.jpg"]'::jsonb WHERE LOWER(name) = LOWER('Quiet Luxury');
-- rebel
UPDATE photo_packages SET "previewUrls" = '["https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/rebel/preview-1.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/rebel/preview-2.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/rebel/preview-3.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/rebel/preview-4.jpg"]'::jsonb WHERE LOWER(name) = LOWER('Rebel');
-- soft-power
UPDATE photo_packages SET "previewUrls" = '["https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/soft-power/preview-1.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/soft-power/preview-2.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/soft-power/preview-3.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/soft-power/preview-4.jpg"]'::jsonb WHERE LOWER(name) = LOWER('Soft Power');
-- summer-vibes
UPDATE photo_packages SET "previewUrls" = '["https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/summer-vibes/preview-1.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/summer-vibes/preview-2.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/summer-vibes/preview-3.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/summer-vibes/preview-4.jpg"]'::jsonb WHERE LOWER(name) = LOWER('Summer Vibes');
-- urban
UPDATE photo_packages SET "previewUrls" = '["https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/urban/preview-1.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/urban/preview-2.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/urban/preview-3.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/urban/preview-4.jpg"]'::jsonb WHERE LOWER(name) = LOWER('Urban');
-- vintage
UPDATE photo_packages SET "previewUrls" = '["https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/vintage/preview-1.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/vintage/preview-2.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/vintage/preview-3.jpg","https://ensaio-fotos-prod.s3.us-east-2.amazonaws.com/package-previews/vintage/preview-4.jpg"]'::jsonb WHERE LOWER(name) = LOWER('Vintage');

-- Verificar resultado:
SELECT id, name, "previewUrls" FROM photo_packages;
